# -- Site Configuration --
# Refer to the theme docs for more details about each of these parameters.
# https://blowfish.page/docs/getting-started/

theme = "blowfish"
baseURL = "https://nstrum.net/"
defaultContentLanguage = "ja"

# pluralizeListTitles = "true" # hugo function useful for non-english languages, find out more in  https://gohugo.io/getting-started/configuration/#pluralizelisttitles

enableRobotsTXT = false
paginate = 10
summaryLength = 0

buildDrafts = false
buildFuture = false

googleAnalytics = "G-YV1NT8TS3B"

[params]
  description = 'モンスターを仲間にできる新感覚マルチサーバー！'
  images = ['default-feature.jpg']
  title = 'Nstrum - ストゥルム'

[imaging]
  anchor = 'Center'

[taxonomies]
  tag = "tags"
  category = "categories"
  author = "authors"
  series = "series"
  rules = "rules"
  plugins = "plugins"

[sitemap]
  changefreq = 'daily'
  filename = 'sitemap.xml'
  priority = 0.5

[outputs]
  home = ["HTML", "RSS", "JSON"]


