# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.
# 
# The simplest menu configuration is to provide:
#   name = The name to be displayed for this menu link
#   pageRef = The identifier of the page or section to link to
#
# By default the menu is ordered alphabetically. This can be
# overridden by providing a weight value. The menu will then be
# ordered by weight from lowest to highest.

[[main]]
  name = "参加する"
  pageRef = "posts"
  weight = 1

[[main]]
  name = "ルール"
  weight = 2

[[main]]
  name = "プラグイン"
  weight = 3

[[main]]
  name = "マイクラモンスターズ"
  parent = "プラグイン"
  pageRef = "posts"
  weight = 31

[[main]]
  name = "その他"
  parent = "プラグイン"
  pageRef = "posts"
  weight = 32

[[main]]
  identifier = "discord"
  pre = "discord"
  url = "https://discord.gg/invitecode"
  weight = 5

[[main]]
  identifier = "twitch"
  pre = "twitch"
  url = "https://twitch.tv/"
  weight = 6

# [[main]]
#  name = "example sub-menu 2"
#  parent = "Parent"
#  pageRef = "posts"
#  weight = 20


# [[subnavigation]]
#  name = "An interesting topic"
#  pageRef = "tags/interesting-topic"
#  weight = 10

#[[subnavigation]]
#  name = "My Awesome Category"
#  pre = "github"
#  pageRef = "categories/awesome"
#  weight = 20

# [[main]]
#  name = "Categories"
#  pageRef = "categories"
#  weight = 20

# [[main]]
#  name = "Tags"
#  pageRef = "tags"
#  weight = 30


# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.


# [[footer]]
#   name = "タグ"
#   pageRef = "tags"
#   weight = 10

# [[footer]]
#   name = "カテゴリ"
#   pageRef = "categories"
#   weight = 20
